/*******************************************************************************
 *  Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 *  The contents of this file are subject to the Mozilla Public License
 *  Version 1.1 (the "License"); you may not use this file except in
 *  compliance with the License. You may obtain a copy of the License at
 *  http://www.mozilla.org/MPL/
 *
 *  Software distributed under the License is distributed on an "AS IS"
 *  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 *  License for the specific language governing rights and limitations
 *  under the License.
 *
 *  The Original Code is ICMA
 *
 *  The Initial Developer of the Original Code is University of Auckland,
 *  Auckland, New Zealand.
 *  Copyright (C) 2011-2014 by the University of Auckland.
 *  All Rights Reserved.
 *
 *  Contributor(s): Jagir R. Hussan
 *
 *  Alternatively, the contents of this file may be used under the terms of
 *  either the GNU General Public License Version 2 or later (the "GPL"), or
 *  the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 *  in which case the provisions of the GPL or the LGPL are applicable instead
 *  of those above. If you wish to allow use of your version of this file only
 *  under the terms of either the GPL or the LGPL, and not to allow others to
 *  use your version of this file under the terms of the MPL, indicate your
 *  decision by deleting the provisions above and replace them with the notice
 *  and other provisions required by the GPL or the LGPL. If you do not delete
 *  the provisions above, a recipient may use your version of this file under
 *  the terms of any one of the MPL, the GPL or the LGPL.
 *
 *
 *******************************************************************************/
package nz.ac.auckland.abi.speckletofem.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-05-13T10:49:49.015+12:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "www.abi.auckland.ac.nz/CCF", name = "SpeckleToFEMModelService")
@XmlSeeAlso({ObjectFactory.class})
public interface SpeckleToFEMModelService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDicom", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.GetDicom")
    @WebMethod
    @ResponseWrapper(localName = "getDicomResponse", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.GetDicomResponse")
    public byte[] getDicom(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submit", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.Submit")
    @WebMethod
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.SubmitResponse")
    public java.lang.String submit(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCompletion", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.GetCompletion")
    @WebMethod
    @ResponseWrapper(localName = "getCompletionResponse", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.GetCompletionResponse")
    public double getCompletion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "cleanUp", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.CleanUp")
    @WebMethod
    @ResponseWrapper(localName = "cleanUpResponse", targetNamespace = "www.abi.auckland.ac.nz/CCF", className = "nz.ac.auckland.abi.speckletofem.wsclient.CleanUpResponse")
    public void cleanUp(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
