/*******************************************************************************
 *  Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 *  The contents of this file are subject to the Mozilla Public License
 *  Version 1.1 (the "License"); you may not use this file except in
 *  compliance with the License. You may obtain a copy of the License at
 *  http://www.mozilla.org/MPL/
 *
 *  Software distributed under the License is distributed on an "AS IS"
 *  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 *  License for the specific language governing rights and limitations
 *  under the License.
 *
 *  The Original Code is ICMA
 *
 *  The Initial Developer of the Original Code is University of Auckland,
 *  Auckland, New Zealand.
 *  Copyright (C) 2011-2014 by the University of Auckland.
 *  All Rights Reserved.
 *
 *  Contributor(s): Jagir R. Hussan
 *
 *  Alternatively, the contents of this file may be used under the terms of
 *  either the GNU General Public License Version 2 or later (the "GPL"), or
 *  the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 *  in which case the provisions of the GPL or the LGPL are applicable instead
 *  of those above. If you wish to allow use of your version of this file only
 *  under the terms of either the GPL or the LGPL, and not to allow others to
 *  use your version of this file under the terms of the MPL, indicate your
 *  decision by deleting the provisions above and replace them with the notice
 *  and other provisions required by the GPL or the LGPL. If you do not delete
 *  the provisions above, a recipient may use your version of this file under
 *  the terms of any one of the MPL, the GPL or the LGPL.
 *
 *
 *******************************************************************************/

package nz.ac.auckland.abi.speckletracking.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpeckleTrackingServiceService", targetNamespace = "www.abi.auckland.ac.nz/CCF", wsdlLocation = "http://localhost:8080/SpeckleTrackingWS/SpeckleTrackingService?wsdl")
public class SpeckleTrackingServiceService
    extends Service
{

    private final static URL SPECKLETRACKINGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SPECKLETRACKINGSERVICESERVICE_EXCEPTION;
    private final static QName SPECKLETRACKINGSERVICESERVICE_QNAME = new QName("www.abi.auckland.ac.nz/CCF", "SpeckleTrackingServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SpeckleTrackingWS/SpeckleTrackingService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPECKLETRACKINGSERVICESERVICE_WSDL_LOCATION = url;
        SPECKLETRACKINGSERVICESERVICE_EXCEPTION = e;
    }

    public SpeckleTrackingServiceService() {
        super(__getWsdlLocation(), SPECKLETRACKINGSERVICESERVICE_QNAME);
    }

    public SpeckleTrackingServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPECKLETRACKINGSERVICESERVICE_QNAME, features);
    }

    public SpeckleTrackingServiceService(URL wsdlLocation) {
        super(wsdlLocation, SPECKLETRACKINGSERVICESERVICE_QNAME);
    }

    public SpeckleTrackingServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPECKLETRACKINGSERVICESERVICE_QNAME, features);
    }

    public SpeckleTrackingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpeckleTrackingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpeckleTrackingService
     */
    @WebEndpoint(name = "SpeckleTrackingServicePort")
    public SpeckleTrackingService getSpeckleTrackingServicePort() {
        return super.getPort(new QName("www.abi.auckland.ac.nz/CCF", "SpeckleTrackingServicePort"), SpeckleTrackingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpeckleTrackingService
     */
    @WebEndpoint(name = "SpeckleTrackingServicePort")
    public SpeckleTrackingService getSpeckleTrackingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("www.abi.auckland.ac.nz/CCF", "SpeckleTrackingServicePort"), SpeckleTrackingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPECKLETRACKINGSERVICESERVICE_EXCEPTION!= null) {
            throw SPECKLETRACKINGSERVICESERVICE_EXCEPTION;
        }
        return SPECKLETRACKINGSERVICESERVICE_WSDL_LOCATION;
    }

}
